services:
  user-service:
    build: .
    container_name: user-service
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=userdb
      - CHOKIDAR_USEPOLLING=true
      - JWT_SECRET=RandomKeyForJWT
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin123
    depends_on:
      - postgres
    networks:
      - peerprep-network

  postgres:
    image: postgres:16-alpine
    container_name: user-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: userdb
    ports:
      - "3010:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./src/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - peerprep-network

volumes:
  postgres-data:

networks:
  peerprep-network:
    name: peerprep-network