name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    concurrency:
      group: deploy
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: create deployment package
        run: zip -r deploy.zip ./ -x "*/node_modules/*" "*/package-lock.json" ".env" "*.git*"

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21

        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: PeerPrep
          environment_name: PeerPrep-env
          version_label: v-${{ github.run_id }}-${{ github.sha }}
          region: ap-southeast-1
          deployment_package: deploy.zip
